name: CI

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      repository:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    name: "Coding Chores"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          fetch-depth: 0

      - name: "Automated Tests"
        uses: wehmoen-dev/ronin-buddy@v1.2.5
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          app_installation_id: ${{ secrets.BUDDY_INSTALLATION_ID }}
          app_private_key: ${{ secrets.BUDDY_PRIVATE_KEY }}
          app_id: ${{ secrets.BUDDY_APP_ID }}
          sentry_dsn: ${{ secrets.SENTRY_DSN }}
